INSERT INTO roles(name, created_time, updated_time)
VALUES ('ROLE_USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('ROLE_SUPER_ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('ROLE_ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);