INSERT INTO products (brands_id, name, image_link, old_price, price, slug, description, type, created_time, updated_time)
VALUES (1, 'Apple Watch Series 6', 'https://hc.com.vn/i/ecommerce/media/GS.008423_FEATURE_92382.jpg', '7990000', '5490000', 'apple-watch-series-6',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        'SMART_WATCH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (1, 'Apple Watch Series 7', 'https://hc.com.vn/i/ecommerce/media/GS.008423_FEATURE_92382.jpg','7990000', '5490000', 'apple-watch-series-7',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        'SMART_WATCH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (2, 'Samsung Galaxy Watch 4 44mm Bạc', 'https://hc.com.vn/i/ecommerce/media/GS.008423_FEATURE_92382.jpg', '9990000', '7490000', 'samsung-galaxy-watch-4-44mm',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        'SMART_WATCH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 'Đồng hồ thông minh Huawei Watch GT Runner', 'https://hc.com.vn/i/ecommerce/media/GS.008423_FEATURE_92382.jpg', '6990000', '5990000',
        'dong-ho-thong-minh-huawei-watch-gt-runner',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        'SMART_WATCH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (4, 'Oppo Watch 46mm', 'https://hc.com.vn/i/ecommerce/media/GS.008423_FEATURE_92382.jpg', '8990000', '6590000', 'oppo-watch-46mm',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        'SMART_WATCH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 'Đồng hồ Garmin MarQ Adventurer', 'https://hc.com.vn/i/ecommerce/media/GS.008423_FEATURE_92382.jpg', '44990000', '43990000', 'garmin-marq',
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        'CLASSIC_WATCH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);